### PR TITLE
Fix bugs of throttling control behavior in flow control module

### LINKED ISSUE #331: [BUG] estimatedQueueingDuration in ThrottlingChecker may overflow, which may cause infinite waiting
## Issue Description

Type: *bug report*

### Describe what happened
image

我加了相关的日志，发现estimatedQueueingDuration的值已经大于int64最大值了，如下
`
{"level":"info","ts":"2020-11-25 13:21:03","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":54006,"ts-ms":1606281663019,"estimatedQueueingDuration":18446744073709551461,"currentTimeNano":1606281663019051949,"interval":1000000}
{"level":"info","ts":"2020-11-25 13:42:38","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":68220,"ts-ms":1606282958743,"estimatedQueueingDuration":18446744073709551330,"currentTimeNano":1606282958743045270,"interval":1000000}
{"level":"info","ts":"2020-11-25 14:30:37","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":101379,"ts-ms":1606285837180,"estimatedQueueingDuration":18446744073709551374,"currentTimeNano":1606285837180360588,"interval":1000000}
{"level":"info","ts":"2020-11-25 14:31:10","caller":"flow/tc_throttling.go:55","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker1","pid":393,"service":"","GoID":101772,"ts-ms":1606285870585,"estimatedQueueingDuration":18446744073709551383,"currentTimeNano":1606285870585095028,"interval":1000000}
{"level":"info","ts":"2020-11-25 14:33:52","caller":"flow/tc_throttling.go:55","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker1","pid":393,"service":"","GoID":103799,"ts-ms":1606286032195,"estimatedQueueingDuration":18446744073709551149,"currentTimeNano":1606286032195488790,"interval":1000000}
{"level":"info","ts":"2020-11-25 14:42:32","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":110865,"ts-ms":1606286552392,"estimatedQueueingDuration":18446744073709551567,"currentTimeNano":1606286552392114392,"interval":1000000}
{"level":"info","ts":"2020-11-25 15:07:57","caller":"flow/tc_throttling.go:55","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker1","pid":393,"service":"","GoID":134835,"ts-ms":1606288077250,"estimatedQueueingDuration":18446744073709551463,"currentTimeNano":1606288077250908120,"interval":1000000}
{"level":"info","ts":"2020-11-25 15:12:25","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":139236,"ts-ms":1606288345973,"estimatedQueueingDuration":18446744073709551309,"currentTimeNano":1606288345973680338,"interval":1000000}
{"level":"info","ts":"2020-11-25 15:21:37","caller":"flow/tc_throttling.go:55","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker1","pid":393,"service":"","GoID":149532,"ts-ms":1606288897647,"estimatedQueueingDuration":18446744073709551198,"currentTimeNano":1606288897647921208,"interval":1000000}
{"level":"info","ts":"2020-11-25 15:35:07","caller":"flow/tc_throttling.go:63","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker2","pid":393,"service":"","GoID":166445,"ts-ms":1606289707601,"estimatedQueueingDuration":18446744073709551294,"currentTimeNano":1606289707601567729,"interval":1000000}
{"level":"info","ts":"2020-11-25 15:50:44","caller":"flow/tc_throttling.go:55","func":"flow.(*ThrottlingChecker).DoCheck","msg":"ThrottlingChecker1","pid":393,"service":"","GoID":188919,"ts-ms":1606290644177,"estimatedQueueingDuration":18446744073709551286,"currentTimeNano":1606290644177611891,"interval":1000000}
`

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by sczyh30**
### Describe what this PR does / why we need it

Fix bugs of throttling control behavior in flow control module, including overflow bug and time unit bug of wait duration.

### Does this pull request fix one issue?

Fixes #331 

### Describe how you did it

- Change semantic of `waitMs` to `nanosToWait` in `TokenResult` and polish related stat slots. Here we SHOULD use nanos instead of millis, or the queueing interval may not be accurate.
- Fix the bug that unsigned `estimatedQueueingDuration` in throttling checker may overflow. Use int64 instead.

### Describe how to verify it

Run the test cases and demo.

### Special notes for reviews

NONE.

### CODE REVIEW

**Comment by sczyh30** [comment]
Also cc @NineSunRD @luckyxiaoqiang @sanxun0325

File: core/base/result.go [hunk 1]
```diff
@@ -58,13 +58,13 @@ func (s TokenResultStatus) String() string {
 type TokenResult struct {
 	status TokenResultStatus
 
-	blockErr *BlockError
-	waitMs   uint64
+	blockErr    *BlockError
+	nanosToWait uint64
```
Comment (louyuting) [inline core/base/result.go:62]: Maybe use time.Duration is better?  So, we need not to honor the time precision

Comment (sczyh30) [reply core/base/result.go]: Good idea. Updated.

**Review by louyuting — APPROVED** [review]
Nice work~
